---
- name: Retrieve hosts with your_tags filter
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve vms from your_location
      azure.azcollection.azure_rm_virtualmachine_info:
      register: retrieved_info

    - name: Print retrieved_info
      ansible.builtin.debug:
        msg: "{{ retrieved_info }}"

    - name: Print tags
      ansible.builtin.debug:
        msg:
          - name: "{{ item.name }}"
          - tags: "{{ item.tags }}"
          - power_state: "{{ item.power_state }}"
      loop: "{{ retrieved_info.vms | list }}"
      loop_control:
         label: "virtual machine info and associated tags"
